spring:
  application:
    name: scheduling-service

# 讯飞 API 配置
xf:
  appId: ${XF_ID}
  secret: ${XF_SECRET}
  key: ${XF_KEY}
deepseek:
  apiKey: ${DEEPSEEK_API_KEY}
  baseUrl: ${DEEPSEEK_BASE_URL}
  model: ${DEEPSEEK_MODEL}
